# Generated by Django 5.0.1 on 2024-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
