# Generated by Django 5.0.1 on 2024-01-23 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_notification_rejection_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="rejection_reason",
        ),
        migrations.AddField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("car_approved", "Car Approved"),
                    ("car_rejected", "Car Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
