# Generated by Django 4.2.1 on 2023-12-27 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0005_carhandling_verification_status_and_more'),
        ('accounts', '0003_alter_useraccount_managers_alter_useraccount_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_amount', models.PositiveIntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.carhandling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendorprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('pickup_date__gte', datetime.datetime(2023, 12, 27, 7, 29, 25, 971034, tzinfo=datetime.timezone.utc))), name='pickup_date must be greater than or equal to today'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('return_date__gt', models.F('pickup_date'))), name='return_date must be greater than pickup_date'),
        ),
    ]
