# Generated by Django 5.0.1 on 2024-01-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_useraccount_online_status"),
        ("user", "0004_alter_booking_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="IDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_photo", models.ImageField(blank=True, null=True, upload_to="")),
                ("back_photo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
    ]
