# Generated by Django 4.2.1 on 2024-01-01 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_transcation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcation',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='pickup_date must be greater than or equal to today',
        ),
        migrations.AddField(
            model_name='booking',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('pickup_date__gte', datetime.datetime(2024, 1, 1, 10, 51, 47, 51644, tzinfo=datetime.timezone.utc))), name='pickup_date must be greater than or equal to today'),
        ),
    ]
