# Generated by Django 4.2.1 on 2024-01-01 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_transcation_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='pickup_date must be greater than or equal to today',
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('pickup_date__gte', datetime.datetime(2024, 1, 1, 14, 17, 23, 757884, tzinfo=datetime.timezone.utc))), name='pickup_date must be greater than or equal to today'),
        ),
    ]
